Likes and comments
twoaxis/social-media-backend pull request #42
Opened 2024-11-25 14:29 UTC by Rynvasis

Add API POST `/posts/postId/like`
Add API PUT `/posts/postId/comment`

2024-11-26 05:28 UTC, Salint requested changes
Also add ability to unlike a post.

2024-11-26 05:28 UTC, Salint commented on src/Controllers/Post.cs
> +                return BadRequest();
Should throw a 409 Conflict instead.

2024-11-26 05:29 UTC, Salint commented
Also return `likeCount`, `isLiked` and `comments` list when getting a post.

2024-11-26 12:15 UTC, Rynvasis commented on src/Controllers/Post.cs
> +                return BadRequest();
okay, I will solve it

2024-11-30 15:22 UTC, Salint approved these changes

2024-11-30 15:22 UTC, merged